# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - shell: bash
      run: |
        mvn -B package --file pom.xml
        java -version && javac -version && mvn -v
        tree -a
        mvn compile
    - name: Upload directory after compiling
      uses: actions/upload-artifact@v2
      with:
        name: target_upload
        path: ./target
  
  test: 
    name: Test project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download directory
        uses: actions/download-artifact@v2
        with:
          name: target_upload
          path: ./target

      - shell: bash
        run: |
          tree -a .
          mvn cobertura:cobertura
          mvn cobertura:dump-datafile
      - uses: codecov/codecov-action@v1
        with:
          verbose: true